formatters:
  colorlog:
    (): colorlog.ColoredFormatter
    datefmt: '%m-%d %H:%M:%S'
    format: '%(asctime)s %(name)s %(process)d %(message)s'

disable_existing_loggers: false

handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console] 