name: fedrcl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.8
  
  # Deep Learning
  - pytorch>=1.11.0
  - torchvision>=0.12.0
  - torchaudio>=0.11.0
  - cudatoolkit=11.3
  
  # Scientific Computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  
  # Image Processing
  - pillow>=9.0.0
  
  # Configuration and Utilities
  - pyyaml>=6.0
  
  # Pip dependencies
  - pip
  - pip:
    - omegaconf>=2.1.0
    - hydra-core>=1.1.0
    - coloredlogs>=15.0
    - wandb>=0.12.0
    - tqdm>=4.60.0
    - tabulate>=0.8.0
    - mlxtend>=0.19.0 